name: Upstream Synchronize

on:
  schedule:
  - cron:  "*/180 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true
        token: ${{ secrets.GITHUB_TOKEN }} 
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "badlogic/pi-mono"
        source_branch: "main"
        destination_branch: "main"
        sync_tags: "true"
        github_token: ${{ secrets.GITHUB_TOKEN }}
